databases:
  - name: audio-db
    plan: free

services:
  - type: web
    name: gradio-audio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: audio-db
          property: connectionString
